<?php
// dynamic_style.php
// Génère du CSS dynamique à partir de paramètres query string.
header('Content-Type: text/css; charset=UTF-8');

// Valeurs par défaut
$defaults = [
    'primary' => '#46b903',
    'accent' => '#0f172a',
    'bg' => '#ffffff',
    'text' => '#0f172a',
    'mode' => 'light', // light | dark
    'radius' => '8px',
    'font' => "'Inter', system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial",
    'base_size' => '16px'
];

// Récupère et sanitize les paramètres
function g($k, $d){
    if (!isset($_GET[$k]) || $_GET[$k] === '') return $d;
    $v = trim($_GET[$k]);
    // autoriser couleurs hex, rgba(), mots simples, nombres avec px/rem
    return htmlspecialchars($v, ENT_QUOTES, 'UTF-8');
}

$p = [];
foreach ($defaults as $k=>$d) $p[$k] = g($k, $d);

// Si mode dark, ajuster valeurs par défaut si non fournies
if ($p['mode'] === 'dark') {
    if ($p['bg'] === $defaults['bg']) $p['bg'] = '#0b1220';
    if ($p['text'] === $defaults['text']) $p['text'] = '#e6eef8';
}

// small helper: ensure units for base_size
if (is_numeric($p['base_size'])) $p['base_size'] = $p['base_size'] . 'px';

// Output CSS variables and some utility classes
echo "/* Dynamic stylesheet generated by PHP */\n";
echo ":root {\n";
echo "  --sf-primary: {$p['primary']};\n";
echo "  --sf-accent: {$p['accent']};\n";
echo "  --sf-bg: {$p['bg']};\n";
echo "  --sf-text: {$p['text']};\n";
echo "  --sf-radius: {$p['radius']};\n";
echo "  --sf-font: {$p['font']};\n";
echo "  --sf-base-size: {$p['base_size']};\n";
echo "}\n\n";

// Basic page styling
echo "*{box-sizing:border-box;}\n";
echo "html,body{height:100%;margin:0;font-family:var(--sf-font);font-size:var(--sf-base-size);background:var(--sf-bg);color:var(--sf-text);}\n";
echo ".container{max-width:920px;margin:2rem auto;padding:1.25rem;background:rgba(255,255,255,0.02);border-radius:calc(var(--sf-radius) + 2px);}\n";

// Buttons
echo ".btn{display:inline-block;padding:0.6rem 1rem;border-radius:var(--sf-radius);border:0;background:var(--sf-primary);color:#fff;text-decoration:none;cursor:pointer;font-weight:700;}\n";
echo ".btn.primary{background:var(--sf-accent);}\n";
echo ".btn.small{padding:0.3rem 0.6rem;font-size:0.9rem;}\n";

// Form controls
echo "label{display:block;margin-bottom:0.75rem;font-weight:600;}\n";
echo "input[type='text'],input[type='email'],input[type='file'],textarea,select,input{width:100%;padding:0.6rem;border:1px solid rgba(15,23,42,0.08);border-radius:calc(var(--sf-radius) - 2px);background:transparent;color:var(--sf-text);}\n";
echo "input:focus,textarea:focus,select:focus{outline:2px solid color-mix(in srgb, var(--sf-primary) 25%, transparent);box-shadow:0 6px 24px rgba(11,22,40,0.06);}\n";

// Card & headings
echo "h1,h2,h3{color:var(--sf-accent);margin:0 0 1rem 0;}\n";
echo "main.container{padding:1.5rem 1.25rem;border-radius:var(--sf-radius);box-shadow:0 10px 30px rgba(2,6,23,0.06);}\n";

// Utilities
echo ".muted{color:rgba(15,23,42,0.5);}\n";
echo ".row{display:flex;gap:1rem;flex-wrap:wrap;}\n";
echo "@media (max-width:720px){ .container{margin:1rem; padding:1rem;} }\n";

// dark-mode helper class
echo ".dark-mode { background: #07101a; color: #e7f0fb; }\n";

// small accessibility improvements
echo "a[role=button],button{border:0;padding:0; font:inherit;}\n";

// end
return;

?>
